# Generated by Django 4.0.2 on 2022-05-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Beats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('estallido', models.IntegerField()),
                ('subido', models.DateField(auto_now_add=True)),
                ('beat', models.FileField(upload_to='media')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
            ],
            options={
                'verbose_name': 'Beat',
                'verbose_name_plural': 'Beats',
            },
        ),
    ]
