# Generated by Django 4.0.2 on 2022-06-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_categoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='beats',
            name='duracion',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
