# Generated by Django 4.0.2 on 2022-09-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_beats_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beats',
            name='duracion',
            field=models.FloatField(),
        ),
    ]
