# Generated by Django 4.1.4 on 2023-03-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_beats_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='beats',
            name='cambio',
            field=models.DecimalField(decimal_places=3, default=480, max_digits=10),
            preserve_default=False,
        ),
    ]
