# Generated by Django 4.1.4 on 2023-04-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='uid',
        ),
    ]
