# Generated by Django 4.1.4 on 2023-04-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_remove_channel_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_token',
        ),
    ]
