# Generated by Django 4.1.4 on 2023-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0003_remove_channel_channel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
